export enum LocalStorageKeys {
  CREATE_ORDER_TECHNICAL_INFORMATION_CONTAINER_FORM = "CREATE_ORDER_TECHNICAL_INFORMATION_CONTAINER_FORM",
  CREATE_ORDER_TECHNICAL_INFORMATION_CONTAINER_LOADED_FILES = "CREATE_ORDER_TECHNICAL_INFORMATION_CONTAINER_LOADED_FILES",
}
