export enum LocalStorageKeys {
  CREATE_ORDER_TECHNICAL_INFORMATION_CONTAINER_FORM = "CREATE_ORDER_TECHNICAL_INFORMATION_CONTAINER_FORM",
  CREATE_ORDER_STEP = "CREATE_ORDER_STEP",
  USER_EDIT_GENERAL = "USER_EDIT_GENERAL",
  USER_EDIT_ABOUT = "USER_EDIT_ABOUT",
}
